version = 0.1
[default.deploy.parameters]
stack_name = "sam-app"
resolve_s3 = true
s3_prefix = "sam-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Region=\"us-east-1\" FrontendUrl=\"http://localhost:3003\" GoogleClientId=\"128876871494-ddangphp27biloi2uoikvr9o21bhgrll.apps.googleusercontent.com\" GoogleClientSecret=\"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\""
image_repositories = []
