AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Authentication Project with Google OAuth

Parameters:
  GoogleClientId:
    Type: String
    Description: Google OAuth Client ID
    Default: 128876871494-tdd9p4khk95q2eih64n8cfn9le2r12vf.apps.googleusercontent.com
  GoogleClientSecret:
    Type: String
    Description: Google OAuth Client Secret
    Default: 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

Resources:
  AuthApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'OPTIONS, POST, GET'"
        AllowHeaders: "'Content-Type, Authorization'"
        AllowOrigin: "'http://localhost:3003'"

  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.9
      CodeUri: ./src
      Environment:
        Variables:
          GOOGLE_CLIENT_ID: !Ref GoogleClientId
          GOOGLE_CLIENT_SECRET: !Ref GoogleClientSecret
          REDIRECT_URI: https://${AuthApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/auth/google/callback
          FRONTEND_URL: http://localhost:3003
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        GoogleAuth:
          Type: Api
          Properties:
            RestApiId: !Ref AuthApi
            Path: /auth/google
            Method: POST
        GoogleAuthCallback:
          Type: Api
          Properties:
            RestApiId: !Ref AuthApi
            Path: /auth/google/callback
            Method: POST

Outputs:
  GoogleAuthEndpoint:
    Description: API Endpoint for Google OAuth
    Value:
      Fn::Sub: https://${AuthApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/auth/google
  GoogleAuthCallbackEndpoint:
    Description: API Callback Endpoint for Google OAuth
    Value:
      Fn::Sub: https://${AuthApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/auth/google/callback
