AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Authentication Project with Google OAuth

Parameters:
  GoogleClientId:
    Type: String
    Description: Google OAuth Client ID
    Default: 128876871494-ddangphp27biloi2uoikvr9o21bhgrll.apps.googleusercontent.com

  GoogleClientSecret:
    Type: String
    Description: Google OAuth Client Secret
    Default: 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

Resources:
  AuthApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: OPTIONS,POST
        AllowHeaders: Content-Type,Authorization
        AllowOrigin: http://localhost:3003

  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.9
      CodeUri: src/lambda/
      Environment:
        Variables:
          GOOGLE_CLIENT_ID: !Ref GoogleClientId
          GOOGLE_CLIENT_SECRET: !Ref GoogleClientSecret
          REDIRECT_URI: https://q01x8trvnb.execute-api.us-east-1.amazonaws.com/Prod/auth/google/callback
          FRONTEND_URL: http://localhost:3003
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: "Allow"
              Action: 
                - "lambda:InvokeFunction"
              Resource: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${AWS::StackName}-AuthFunction-${AWS::Region}"
      Events:
        GoogleAuth:
          Type: Api
          Properties:
            RestApiId: !Ref AuthApi
            Path: /auth/google
            Method: POST
        GoogleAuthCallback:
          Type: Api
          Properties:
            RestApiId: !Ref AuthApi
            Path: /auth/google/callback
            Method: POST
        GoogleAuthOptions:
          Type: Api
          Properties:
            RestApiId: !Ref AuthApi
            Path: /auth/google
            Method: OPTIONS
        GoogleAuthCallbackOptions:
          Type: Api
          Properties:
            RestApiId: !Ref AuthApi
            Path: /auth/google/callback
            Method: OPTIONS

Outputs:
  GoogleAuthEndpoint:
    Description: API Endpoint for Google OAuth
    Value: !Sub https://${AuthApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/auth/google
  GoogleAuthCallbackEndpoint:
    Description: API Callback Endpoint for Google OAuth
    Value: !Sub https://${AuthApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/auth/google/callback
